#603 add back DL linking
- Does not compile on Ubuntu / Clang 9 when DL linkage is removed.
  (Maybe meaning to remove usages as well-?)

      /usr/bin/ld: ../src/libvt-debug.a(runtime.cc.o):
      undefined reference to symbol 'dladdr@@GLIBC_2.2.5'

  Used in stack_out.h